version: '2'
services:
    common:
        build: .
        environment:
            TZ: "${COMMON_TZ}"
            PUID: "${COMMON_PUID}"
            PGID: "${COMMON_PGID}"
        restart: unless-stopped
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /dev/rtc:/dev/rtc:ro
