version: '2'
services:
    portainer:
        # https://hub.docker.com/r/hypriot/rpi-portainer
        container_name: portainer
        extends:
            file: common.yml
            service: common
        expose:
            - "9000"
        image: "hypriot/rpi-portainer"
        volumes:
            - ./volumes/portainer/data:/data
            - /var/run/docker.sock:/var/run/docker.sock
    letsencrypt:
        # https://hub.docker.com/r/lsioarmhf/letsencrypt
        container_name: letsencrypt
        environment:
            EMAIL: "kylemharding@gmail.com"
            URL: "klutchell.com"
            SUBDOMAINS: "home"
            ONLY_SUBDOMAINS: "true"
        extends:
            file: common.yml
            service: common
        image: "lsioarmhf/letsencrypt"
        ports:
            - "80:80/tcp"
            - "443:443/tcp"
        privileged: true
        volumes:
            - ./volumes/letsencrypt/config:/config
    motioneye:
        # https://hub.docker.com/r/vividboarder/rpi-motioneye
        # https://github.com/ViViDboarder/docker-rpi-motioneye
        container_name: motioneye
        image: vividboarder/rpi-motioneye
        volumes:
            - ./volumes/motioneye/config:/etc/motioneye
            - /mnt/usbstorage/motioneye:/var/lib/motioneye
        extends:
            file: common.yml
            service: common
        expose:
            - "8765"
        restart: unless-stopped
        privileged: true